### PR TITLE
issue #33 Update Scope Statement for Jakarta Common Annotations Project

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by m0mus** [comment]
We will be able to merge it after the scope statement for this project is officially approved.

**Comment by rotty3000** [comment]
Among other examples I've seen a variation of `Java(TM)` and `Java(R)`. I'd also like to clarify if the `Java SE` and `Java EE` usages also require one of the two marks.

**Comment by bshannon** [comment]
Per the [Oracle trademark guidelines](https://www.oracle.com/legal/trademarks.html), just "Java" is fine, but documents should include this credit line on the copyright page:

> Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.

**Comment by rotty3000** [comment]
> should include this credit line on the copyright page

@bshannon does this mean a new `COPYRIGHT.md` document?

**Comment by bshannon** [comment]
IANAL!  :-)

It should definitely be on the copyright page of the spec (assuming the term "Java"
appears in the spec somewhere).

I don't know whether it needs to appear anywhere else on these project pages and if so where.
Possibly it should be in the NOTICE file.

The Oracle trademark guidelines says:
> All products, packaging, manuals, advertisements, promotional materials and Web pages bearing Oracle trademarks should include the following trademark credit line.
> 
> "Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners."
> 
> The credit line may appear anywhere on the collateral, but typically is displayed on a copyright page, the back of a package or at the end of a document or web page.

I'll leave it to you to interpret that in the context of these project pages. :-)

**Comment by edbratt** [comment]
I "vote" for the NOTICE file, but I believe that is auto generated by 
something maintained at Eclipse. Perhaps we should contact our Eclipse 
mentor to find out if that's the case and if so, how can we update this.

**Pull request merged**
